---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: enable-ip-forwarding
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Enable IP forwarding for the secondary interface
      include=openshift-control-plane
      [sysctl]
      net.ipv4.conf.ens4f1.forwarding=1
    name: enable-ip-forwarding
  recommend:
  - priority: 10
    profile: enable-ip-forwarding
